operations/urls.py
from django.conf.urls import patterns, include, url
from operations.views import move_parts
from operations.views import view_part_to_move
from operations.views import admin_rma_extra_fields
from operations.views import reassign_customers_to_customer_sites
from operations.views import view_customer_site_to_reassign
from operations.views import check_if_site_exists_and_reassign
from operations.views import assign_customer_select_customer
from operations.views import assign_customer_to_site_new_customer
from operations.views import manage_users_roles
from operations.views import manage_user_roles
from operations.views import change_password
urlpatterns = patterns('',
    url(r'move_parts/$', move_parts, name='move_parts'),
    url(r'admin_rma_extra_fields/$', admin_rma_extra_fields, name='admin_rma_extra_fields'),
    url(r'show_part_to_move/(?P<id>\d+)$', view_part_to_move, name='view_part_to_move'),
    url(r'view_customer_site_to_reassign/(?P<id>\d+)$', view_customer_site_to_reassign, name='view_customer_site_to_reassign'),
    url(r'edit_customer_site/(?P<id>\d+)$', check_if_site_exists_and_reassign, name='operations_edit_customer_site'),
    url(r'assign_customer_select_customer/(?P<id>\d+)$', assign_customer_select_customer, name='assign_customer_select_customer'),
    url(r'assign_customer_to_site_new_customer/(?P<id>\d+)$', assign_customer_to_site_new_customer, name='assign_customer_to_site_new_customer'),
    url(r'reassign_customers_to_customer_sites/$', reassign_customers_to_customer_sites, name='reassign_customers_to_customer_sites'),
    url(r'manage_users_roles/$', manage_users_roles, name='manage_users_roles'),
    url(r'manage_user_roles/(?P<id>\d+)$', manage_user_roles, name='manage_user_roles'),
    url(r'change_password/$', change_password, name='change_password'),
)

parts/urls.py
from django.conf.urls import patterns, include, url
from parts.views import index
from parts.views import view
from parts.views import PartUpdateView
from parts.views import PartUpdateOpsView
from parts.views import PartCreateView
from parts.views import PartDeleteView
from parts.views import PartDeleteOpsView
from django.contrib.auth.decorators import login_required
urlpatterns = patterns('',
    url(r'^$', index, name='list_parts'),
    url(r'show/(?P<id>\d+)$', view, name='view_part'),
    url(r'create/$', login_required(PartCreateView.as_view()), name='create_part'),
    url(r'delete/(?P<id>\d+)$', login_required(PartDeleteView.as_view()), name='delete_part'),
    url(r'delete-ops/(?P<id>\d+)$', login_required(PartDeleteOpsView.as_view()), name='delete_part_ops'),
    url(r'edit/(?P<id>\d+)$', login_required(PartUpdateView.as_view()), name='edit_part'),
    url(r'edit-ops/(?P<id>\d+)$', login_required(PartUpdateOpsView.as_view()), name='edit_part_ops'),
)

rma/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
urlpatterns = patterns('',
    url(r'^'+settings.SUB_URL+'$', include('return_merchandise_authorizations.urls')),
    url(r'^'+settings.SUB_URL+'rma/', include('return_merchandise_authorizations.urls')),
    url(r'^'+settings.SUB_URL+'parts/', include('parts.urls')),
    url(r'^'+settings.SUB_URL+'returned_items/', include('returned_items.urls')),
    url(r'^'+settings.SUB_URL+'services/', include('services.urls')),
    url(r'^'+settings.SUB_URL+'rma_attachments/', include('rma_attachments.urls')),
    url(r'^'+settings.SUB_URL+'networks/', include('site_networks.urls')),
    url(r'^'+settings.SUB_URL+'commissioned-sites/', include('commissioned_sites.urls')),
    url(r'^'+settings.SUB_URL+'operations/', include('operations.urls')),
    url(r'^'+settings.SUB_URL+'customers/', include('customers.urls')),
    url(r'^'+settings.SUB_URL+'reports/', include('reports.urls')),
    url(r'^'+settings.SUB_URL+'admin/', include(admin.site.urls)),
)

parts/models.py
from django.db import models


from django.contrib.auth.models import User
from django.db import models

from django.core.urlresolvers import reverse

from django.db.models.signals import pre_save
from django.dispatch import receiver
from datetime import datetime as dt
from return_merchandise_authorizations.settings import YES_NO_CHOICES

class Part(models.Model):
    """
    Return Merchandise Authorization
    belongs to Customer
    """
    description = models.CharField(max_length = 100)
    note = models.TextField(max_length = 300, null=True, blank=True)
    model_number = models.CharField(max_length=90, blank=True, null=True)
    type = models.CharField(max_length=90, blank=True, null=True)
    official_model_name = models.CharField(max_length = 100, null=True, blank=True)
    part_number = models.CharField(max_length=90, blank=True, null=True)

    end_of_life = models.PositiveSmallIntegerField(choices=YES_NO_CHOICES,  default=1) # no
    last_modified_by = models.ForeignKey(User, null=True, blank=True)
    last_modified_on = models.DateField(null=True)

    def get_absolute_url(self):
        return reverse("view_part", kwargs={"id": self.id})
    def __unicode__(self):
        return '[description: %s, model_number:%s, type: %s, official_model_name: %s]'%(
                    self.description, self.model_number, self.type, self.official_model_name,
        )
    class Meta:
        verbose_name_plural = "Parts"
        ordering = ["description", "model_number"]

@receiver(pre_save, sender=Part)
def part_save_handler(sender, **kwargs):
    part = kwargs['instance']
    part.last_modified_on = dt.now()

operations/forms.py
__author__ = 'marc'

from django import forms
from customers.models import Customer
from customers.models import CustomerCompany


class CustomerCompanyAndSiteNameForm(forms.Form):

    customer = forms.IntegerField(widget = forms.Select(choices = [ ]), label='Select Customer')
    name = forms.CharField(label='Site Name')
    def __init__(self, *args, **kwargs):
        # This should be done before any references to self.fields
        super(CustomerCompanyAndSiteNameForm, self).__init__(*args, **kwargs)
        companies = CustomerCompany.objects.exclude(company_name='UNKNOWNCOMPANY').order_by('company_name')

        cchoices = []
        for y in companies:
            cchoices.append((y.id, "%s"%(y.company_name)))

        self.fields['customer'].widget.choices = cchoices

class change_password_form(forms.Form):

    newpassword1 = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'type':'password', 'placeholder':'New Password',  'class' : 'span'}))
    newpassword2 = forms.CharField(max_length = 20, widget=forms.TextInput(attrs={'type':'password', 'placeholder':'Confirm New Password',  'class' : 'span'}))

    def clean(self):
        if 'newpassword1' in self.cleaned_data and 'newpassword2' in self.cleaned_data:
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data

parts/forms.py
__author__ = 'marc'
from django.forms import ModelForm
from parts.models import Part
from django import forms

class PartForm(ModelForm):
    class Meta:
        model = Part
        fields = ['description', 'model_number', 'note', 'official_model_name', 'part_number', 'end_of_life']

class ItemsMoveForm(forms.Form):
    destination_part = forms.IntegerField(widget = forms.Select(choices = [ ]), label='Move returned items to')

    def __init__(self, part, *args, **kwargs):
        # This should be done before any references to self.fields
        super(ItemsMoveForm, self).__init__(*args, **kwargs)

        # Change the field options
        parts = Part.objects.all()
        choices = []

        for p in parts:
            if p.id != part.id:
                choices.append((p.id, "%s-%s"%(p.description, p.model_number)))
        self.fields['destination_part'].widget.choices = choices

operations/views.py
import redis
import json
import re
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate
from parts.forms import ItemsMoveForm
from return_merchandise_authorizations.models import Rma
from return_merchandise_authorizations.models import Item
from parts.models import Part
from customers.models import CustomerCompany
from customers.forms import CustomerForm
from customers.forms import CustomerSiteIdNameForm
from operations.forms import CustomerCompanyAndSiteNameForm
from operations.forms import change_password_form
from return_merchandise_authorizations.lib import site_autocomplete_dropdown_selections
from return_merchandise_authorizations.acl import user_role
from return_merchandise_authorizations.acl import admin_role_required
from customers.models import Customer

from return_merchandise_authorizations.acl import user_role_required
@login_required
def reassign_customers_to_customer_sites(request):
    """
    show list of sites belonging to unknown company
    :param request:
    :return:
    """
    sites = Customer.objects.filter(customer__company_name = 'UNKNOWNCOMPANY').order_by('name')
    return render(request, 'operations/sites_index.html',
                  {'sites': sites},
        context_instance=RequestContext(request))

@login_required
def admin_rma_extra_fields(request):
    r = redis.StrictRedis(host='localhost', port=6379, db=settings.SESSION_REDIS_DB)
    message = ''
    if request.method == 'GET':
        rfields = json.loads(r.get(settings.SUB_URL.replace('/','')+':rma_extra_data'))
        #rfields = ['a', 'b']
        fields = []
        i = 0
        for f in rfields:
            obj = {
                'key': 'key_'+str(i),
                'value': f
            }
            i += 1
            fields.append(obj)
    if request.method == 'POST':
        #
        # Save to Redis
        #
        if request.POST['new_field'] == 'yes':
            # new empty field requested
            #
            # put keys in sortable-on-order dictionary
            rfields = []
            for k in request.POST.keys():
                if re.search('^key_', k) and request.POST[k] != '':
                    rfields.append({
                        'value': request.POST[k]
                    })
            rfields_sorted = sorted(rfields, key=lambda k: k['value'])
            fields = []
            i = 0
            for f in rfields_sorted:
                obj = {
                    'key': 'key_'+str(i),
                    'value': f['value']
                }
                i += 1
                fields.append(obj)
            fields.append({
                'key': 'key_'+str(i),
                'value': ''
            })

        else:
            # save and return with save message.

            fields = []
            rfields = []
            i = 0
            for k in request.POST.keys():
                if re.search('^key_', k) and request.POST[k] != '':
                    rfields.append(request.POST[k])
                    obj = {
                        'key': 'key_'+str(i),
                        'value': request.POST[k]
                    }
                    i += 1
                    fields.append(obj)

            r.set(settings.SUB_URL.replace('/','')+':rma_extra_data', json.dumps(sorted(rfields)))
            message = 'Field Names Saved'
    return render(request, 'operations/admin_rma_extra_fields.html',
                  {'fields': fields,
                   'message': message
                  },
        context_instance=RequestContext(request))

@login_required
def move_parts(request):
    parts = Part.objects.all()
    parts_count = []
    for p in parts:
        mod_part = {
            'id': p.id,
            'description': p.description,
            'model_number': p.model_number,
            'count': len(Item.objects.filter(part=p))
        }
        parts_count.append(mod_part)
    return render(request, 'operations/parts_index.html',
                  {'parts': parts_count},
        context_instance=RequestContext(request))

@login_required
def assign_customer_to_site_new_customer(request, id):

    if request.method == 'GET':
        site = Customer.objects.get(pk=id)
        site_rmas = Rma.objects.filter(customer=site)
        customer_name_form = CustomerForm()
        site_form = CustomerSiteIdNameForm(instance=site)
        return render(request, 'operations/edit_site_new_customer.html',
                  {
                      'site': site,
                      'customer_name_form': customer_name_form,
                      'site_form': site_form,
                      'site_rmas': site_rmas
                  },
        context_instance=RequestContext(request))

    if request.method == 'POST':
        site = Customer.objects.get(pk=id)
        error_count = 0
        customer_name_form = CustomerForm(request.POST)
        site_form = CustomerSiteIdNameForm(request.POST, instance=site)
        site_rmas = Rma.objects.filter(customer=site)
        if site_form.is_valid() is not True:
            error_count += 1
        if customer_name_form.is_valid() is not True:
            error_count += 1

        if error_count > 0:
            return render(request, 'operations/edit_site_new_customer.html',
                {
                      'site': site,
                      'customer_name_form': customer_name_form,
                      'site_form': site_form,
                      'site_rmas': site_rmas,
                },
                context_instance=RequestContext(request))
        else:
            new_customer = customer_name_form.save()
            new_customer_site = Customer()
            new_customer_site.name = site_form.cleaned_data['name']
            new_customer_site.customer = new_customer
            new_customer_site.save()

            return HttpResponseRedirect(reverse('view_customer_site_to_reassign', kwargs={'id': new_customer_site.id}))
@login_required
def view_part_to_move(request, id):
    if request.user.groups.filter(name='user').exists() is False:
            return render(request, 'errors/operation_not_allowed.html',
                  {},
        context_instance=RequestContext(request))
    else:
        part = Part.objects.get(pk=id)
        items = Item.objects.filter(part=id)
        return render(request, 'operations/view_part_to_move.html',
                      { 'part': part,
                        'items': items,
                        'item_count': len(items),
                        'form': ItemsMoveForm(part)
                      },
            context_instance=RequestContext(request))

@login_required
def view_customer_site_to_reassign(request, id):
    site = Customer.objects.get(pk=id)
    site_rmas = Rma.objects.filter(customer=site)
    return render(request, 'operations/view_site_to_reassign.html',
                  {
                      'site': site,
                      'site_rmas': site_rmas,
                  },
        context_instance=RequestContext(request))

@login_required
def assign_customer_select_customer(request, id):
    """
    Have user decide if site exists from list and reassign all rma to selected site and delete site
    :param request:
    :param id:
    :return:
    """
    site = Customer.objects.get(pk=id)
    site_rmas = Rma.objects.filter(customer=site)
    if request.method == 'GET':
        data = {
            'name': site_rmas[0].customer.name,
        }
        customer_name_site_form = CustomerCompanyAndSiteNameForm(initial=data)
        return render(request, 'operations/assign_customer_select_customer.html',
                  {
                      'site': site,
                      'form': customer_name_site_form,
                      'site_rmas': site_rmas
                  },
        context_instance=RequestContext(request))
    if request.method == 'POST':
        customer_name_site_form = CustomerCompanyAndSiteNameForm(request.POST)
        if customer_name_site_form.is_valid():

            new_site_name = customer_name_site_form.cleaned_data['name']
            existing_customer_id = int(customer_name_site_form.cleaned_data['customer'])
            existing_customer = CustomerCompany.objects.get(pk=existing_customer_id)
            new_site = Customer()
            new_site.customer = existing_customer
            new_site.name = new_site_name
            new_site.save()
            for s in site_rmas:
                s.customer = new_site
                s.save()
            site.delete()

            return HttpResponseRedirect(reverse('reassign_customers_to_customer_sites'))
        else:
            return render(request, 'operations/assign_customer_select_customer.html',
                      {
                          'site': site,
                          'form': customer_name_site_form,
                          'site_rmas': site_rmas
                      },
            context_instance=RequestContext(request))

@login_required
@user_role_required
def check_if_site_exists_and_reassign(request, id):
    """
    Have user decide if site exists from list and reassign all rma to selected site and delete site
    :param request:
    :param id:
    :return:
    """
    site = Customer.objects.get(pk=id)
    site_rmas = Rma.objects.filter(customer=site)
    if request.method == 'GET':
        return render(request, 'operations/edit_site.html',
                      {
                        'sites': site_autocomplete_dropdown_selections(),
                        'site': site,
                        'site_rmas': site_rmas,
                      },
            context_instance=RequestContext(request))

operations/templates/operations/_admin_dropdown_menu_list.html
{% load admin_url %}
{% load user_group %}
<li><a id='change-password-nav' href="{% url 'change_password' %}">Change Password</a></li>
{% if request.user|has_group:"poweruser" %}
    <li><a id='admin-edit-rma-extra-fields-nav' href="{% url 'admin_rma_extra_fields' %}">RMA Custom Fields</a></li>
{% endif %}
{% if request.user|has_group:"admin" %}
    <li id='django-admin-nav'>{%  admin_panel_url %}</li>
{% endif %}

operations/templates/operations/_customer_site_move_rma_header.html
<h1>Reassign RMAs of UNKNOWNCOMPANY's site to a good known site already established.</h1>
<h2>{{  site.customer.company_name  }}-{{  site.name  }}</h2>

operations/templates/operations/_dropdown_menu_list.html
{% load user_group %}
<li>
    <a id='move-parts-app-nav-button' href="{% url 'move_parts' %}">Parts</a>
    <a id='reassign-customers-to-customer-sites-app-nav-button' href="{% url 'reassign_customers_to_customer_sites' %}">Customer RMA Sites</a>
    {% if request.user|has_group:"admin" %}
        <a id='manage-user-roles' href="{% url 'manage_users_roles' %}">Manage User Roles</a>
    {% endif %}
</li>

operations/templates/operations/_new_site_or_customer_button.html
<p>Don't See the customer AND customer site, combined? <button class="btn primary btn-warning" id='redirect-to-assign-customer-select-customer'>press here</button></p>

operations/templates/operations/_part_view.html
<div class="row">
    <div class="col-md-4 field-name">Description</div>
    <div class="col-md-8 data"> {{  part.description  }}</div>
</div>
<div class="row">
    <div class="col-md-4 field-name">Note</div>
    <div class="col-md-8 data">
        {{  part.note}}
    </div>
</div>
<div class="row">
    <div class="col-md-4 field-name">Model Number</div>
    <div class="col-md-8 data">
        {{  part.model_number }}
    </div>
</div>
<div class="row">
    <div class="col-md-12 field-name">
        Returned Parts
    </div>
</div>
<form id='move-part' action="{% url 'confirm_move_items' %}" method="POST">{% csrf_token %}
        <table>
            <div class="row">
                <div class="col-md-12 data">
                     <input id="select-all-return-items" type="checkbox">&nbsp;SELECT ALL
                </div>
            </div>
            <div id="returned-items-list">
                <div class="row list-header">
                    <div class="col-md-3 data">Date Customer</div>
                    <div class="col-md-2 data">Description</div>
                    <div class="col-md-2 data">Quantity</div>
                    <div class="col-md-5 data">Note</div>
                </div>
                {% for i in items %}
                <div class="row">
                    <div class="col-md-3 data">
                    <input type="checkbox" name="part-{{ i.id }}" value="{{ i.id }}">
                        {{  i.rma.date }}&nbsp;{{  i.rma.customer.name }}
                    </div>
                    <div class="col-md-2 data">
                        {{  i.part.description }}
                    </div>
                    <div class="col-md-2 data">
                        {{  i.quantity }}
                    </div>
                    <div class="col-md-5 data">
                        {{  i.note }}
                    </div>
                </div>
                {% endfor %}
            </div>

            {{ form.as_table }}
            <input class="btn primary" id='move-parts-button' type="submit" value="Move Returned Items" />
        </table>
</form>
<div class="row">
    <div class="col-md-12 field-name-small">Last Modified By {{ user.username }} - {{ user.username.first }} {{ user.username.last }}</div>
</div>

operations/templates/operations/_site_rmas.html
{% load cycle from future %}
<h3>RMAs assigned to this site</h3>
<div class="row">
    <div class="col-md-2 field-name">Reference Number</div>
    <div class="col-md-2 field-name">Date</div>
    <div class="col-md-3 field-name">Address</div>
    <div class="col-md-3 field-name">Contact</div>
    <div class="col-md-2 field-name">Contact Phone</div>
</div>
{% for i in site_rmas %}
    <div class="row  {% cycle 'odd-row' 'even-row' %}">
        <div class="col-md-2">
            {{ i.reference_number }}
        </div>
        <div class="col-md-2">
            {{ i.date }}
        </div>
        <div class="col-md-3">
            {{ i.address }}
        </div>
        <div class="col-md-3">
            {{ i.contact }}
        </div>
        <div class="col-md-2">
            {{ i.contact_phone_number }}
        </div>
    </div>
{% endfor %}

operations/templates/operations/_view_site.html
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12 field-name"><h3>Customer Data</h3></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4 field-name">Customer Name</div>
                    <div class="col-md-8 data"> {{  site.customer.company_name  }}</div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-4 field-name">Site Name</div>
                    <div class="col-md-8 data"> {{  site.name  }}</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 field-name-small">Last Modified By {{ user.username }} - {{ user.username.first }} {{ user.username.last }}</div>
        </div>
    </div>
</div>

operations/templates/operations/admin_commissioned_sites_extra_fields.html
{% extends "base.html" %}

{% load cycle from future %}
{% block content %}


<script src="{{ STATIC_URL   }}js/jquery.tablednd.js"></script>
    <div class="container">

        {% if user.is_authenticated %}
            <div class="page-header">
                <h1>Commissioned Sites - Extra Data Fields</h1>
                <p class="lead">User Defined Fields</p>
                {% if message %}
                    <p class="error-message">{{ message }}</p>
                {% endif %}
            </div>
            <form method="POST">{% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        <div id="fields">
                            <div  class="row">
                            <table id="keyword-table" border="1">
                            {% for i in fields %}
                                    <tr class="{% cycle 'odd-row' 'even-row' %}">
                                            <td><input type='text' name="{{ i.key }}" value="{{ i.value }}"></td>
                                    </tr>
                            {% endfor %}
                            </table>
                            </div>
                        </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="margin-bottom: 16px">
                        <button class="btn primary btn-warning" id='add-extra-field'>Add New Field</button>
                    </div>
                    <div class="col-md-12" style="margin-bottom: 16px">
                        <button class="btn primary btn-warning" id='add-extra-field'>Save Extra Data Field Names</button>
                    </div>
                </div>
                <input type='hidden' id='new_field' name="new_field" label="new_field" value="no">
            </form>
        {% else %}
            <h1>Please Log In</h1>
        {% endif %}
    </div>
    <script src="{{ STATIC_URL   }}js/site_extrafields.js"></script>

{% endblock content %}

operations/templates/operations/change_password.html
{% extends "base_form.html" %}
{% block content %}
    <div class="container">
    <div class="page-header">{% include "operations/_password_reset_header.html" %}</div>
        <div class='row'>{{ error }}</div>
        <table>
            <form action="" method="post">{% csrf_token %}
                {{ form.as_table }}
                <input id='submit-new-site-selected-for-rma-moving' class="btn primary btn-success" type="submit" value="Change Password" />
                <button class="btn primary btn-warning" type="submit" id="password-reset-cancel-button">CANCEL</button>
            </form>
        </table>
    </div>
    <script type="text/javascript">
        var cancel_url = "{% url 'home_page' %}";
        $('#password-reset-cancel-button').click(function(e) {
            window.location.replace(cancel_url);
            e.preventDefault()
        });
    </script>
{% endblock content %}

operations/templates/operations/edit_site.html
{% extends "base_form.html" %}
{% block content %}
    <div class="container">
    <div class="page-header">{% include "operations/_customer_site_move_rma_header.html" %}</div>
    <form action="" method="post">{% csrf_token %}
        {% include "operations/_new_site_or_customer_button.html" %}
        <input id="id_customer" name="customer" readonly="readonly" type="text" style="display: none"/>
	    <input id="autocomplete" name="customer-auto" size=70 type="text" placeholder="Type a few characters of the client or site or address">
        <input id='submit-new-site-selected-for-rma-moving' class="btn primary btn-success" type="submit" value="Save Move RMAs Below to this Customer Site" />
    </form>
    <a class="btn primary btn-warning" href="{% url 'view_customer_site_to_reassign' id=site.id  %}">CANCEL</a>
    {% include "operations/_site_rmas.html" %}
    <script>
        var sites = {{ sites | safe }};
        var assign_customer_select_customer = '{{ sub_url }}operations/assign_customer_select_customer';
        var site_id = {{ site.id }};
    </script>
    <script src="{{ STATIC_URL }}js/operations.js"></script>

    <script src="{{ STATIC_URL   }}js/site_edit.js"></script>
    <script src="{{ STATIC_URL   }}return_merchandise_authorizations/js/highlight.js"></script>
    <script src="{{ STATIC_URL   }}return_merchandise_authorizations/js/sites-autocomplete.js"></script>
{% endblock content %}

operations/templates/operations/manage_user_roles.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="page-header">{% include "operations/_user_roles_header.html" %}</div>
    <div class="row">
        <a  class="btn btn-success" id='manage-user-roles' href="{% url 'manage_users_roles' %}">Cancel/Finished</a>
    </div>
    <div class="row">
        <div class="col-md-12" id="results">
        </div>
        <div class="col-md-12" style="margin-bottom: 16px">
                <form>
                    <select name="role" id="run-selected-role-change">
                      <option value="NON-OP">Select a Role</option>
                        {% if role != 'user' %}
                            <option value="user">User</option>
                        {% else %}
                            <option value="user" selected="selected">User</option>
                        {% endif %}
                        {% if role != 'admin' %}
                            <option value="admin">Admin</option>
                        {% else %}
                            <option value="admin" selected="selected">Admin</option>
                        {% endif %}
                        {% if role != 'poweruser' %}
                            <option value="poweruser">Poweruser</option>
                        {% else %}
                            <option value="poweruser" selected="selected">Poweruser</option>
                        {% endif %}
                        {% if role != 'approver' %}
                            <option value="approver">Approver</option>
                        {% else %}
                            <option value="approver" selected="selected">Approver</option>
                        {% endif %}
                        {% if role != 'viewer' %}
                            <option value="viewer">Viewer</option>
                        {% else %}
                            <option value="viewer" selected="selected">Viewer</option>
                        {% endif %}
                    </select>
                </form>
        </div>
    </div>
    <script>
        var id = {{ user.id }};
        var assign_role_url =  '{{ sub_url }}services/assign_role/';
    </script>
    <script src="{{ STATIC_URL   }}js/operations.js"></script>
{% endblock content %}

operations/templates/operations/manage_users_roles.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <div class="page-header">{% include "operations/_users_roles_header.html" %}</div>
    <div class="row">
        <div class="col-md-12">
            <h3>Users Roles</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" style="margin-bottom: 16px">
            <table>
                <tr>
                    <th>User</th>
                    <th>Role</th>
                </tr>
                {% for u in users_roles %}
                    <tr class="user-role-result">
                        <td><a href="{% url 'manage_user_roles' id=u.user.id  %}">{{ u.user.username }}</a></td>
                        <td><a href="{% url 'manage_user_roles' id=u.user.id  %}">{{ u.role }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <script src="{{ STATIC_URL   }}js/operations.js"></script>
{% endblock content %}